DEMO_CONTENT = [
    {
        "term": "Prompt",
        "meaning": "提示词",
        "explanation": "提供给模型的指令、问题或上下文，用于引导模型生成结果。",
        "example_en": "A clear prompt usually produces a more useful answer.",
        "example_cn": "清晰的提示词通常能产生更有用的回答。",
        "question": "Prompt 在生成式 AI 中通常指什么？",
        "options": ["A. 模型参数", "B. 给模型的输入或指令", "C. 训练服务器"],
        "answer": "B",
        "difficulty": 1,
        "topic": "AI Basics",
    },
    {
        "term": "Token",
        "meaning": "词元",
        "explanation": "模型处理文本时使用的基本单位，可以是一个词、词的一部分或标点。",
        "example_en": "The model converts the sentence into tokens before processing it.",
        "example_cn": "模型在处理句子前会先把它转换成词元。",
        "question": "Token 最接近下面哪个概念？",
        "options": ["A. 文本处理的基本单位", "B. 用户账号", "C. 数据库表"],
        "answer": "A",
        "difficulty": 1,
        "topic": "LLM",
    },
    {
        "term": "Inference",
        "meaning": "推理",
        "explanation": "训练完成后，模型使用已有参数处理新输入并生成结果的过程。",
        "example_en": "The device can run AI inference locally.",
        "example_cn": "这台设备可以在本地运行 AI 推理。",
        "question": "Inference 一般发生在哪个阶段？",
        "options": ["A. 模型使用阶段", "B. 数据标注之前", "C. 服务器采购阶段"],
        "answer": "A",
        "difficulty": 1,
        "topic": "LLM",
    },
    {
        "term": "Fine-tuning",
        "meaning": "微调",
        "explanation": "在预训练模型基础上，使用特定数据继续训练，以适应特定任务。",
        "example_en": "The team fine-tuned the model on customer service conversations.",
        "example_cn": "团队使用客服对话数据对模型进行了微调。",
        "question": "Fine-tuning 的主要目的是什么？",
        "options": ["A. 删除模型", "B. 让模型适应特定任务", "C. 加快网络速度"],
        "answer": "B",
        "difficulty": 2,
        "topic": "Training",
    },
    {
        "term": "Hallucination",
        "meaning": "幻觉",
        "explanation": "模型生成听起来合理、但事实上错误或没有依据的信息。",
        "example_en": "Retrieval can reduce hallucination, but it cannot eliminate it completely.",
        "example_cn": "检索可以减少幻觉，但不能完全消除它。",
        "question": "AI hallucination 指什么？",
        "options": ["A. 模型生成无依据的信息", "B. 屏幕故障", "C. 用户忘记密码"],
        "answer": "A",
        "difficulty": 2,
        "topic": "AI Safety",
    },
    {
        "term": "Context window",
        "meaning": "上下文窗口",
        "explanation": "模型一次请求中能够处理和参考的 token 范围。",
        "example_en": "A larger context window allows the model to read longer documents.",
        "example_cn": "更大的上下文窗口让模型能够读取更长的文档。",
        "question": "更大的 context window 通常意味着什么？",
        "options": ["A. 能处理更长的上下文", "B. 屏幕更大", "C. 训练一定更快"],
        "answer": "A",
        "difficulty": 2,
        "topic": "LLM",
    },
    {
        "term": "Embedding",
        "meaning": "嵌入向量",
        "explanation": "将文本、图片等内容转换成数值向量，用于表示语义并计算相似度。",
        "example_en": "We use embeddings to find semantically similar documents.",
        "example_cn": "我们使用嵌入向量寻找语义相似的文档。",
        "question": "Embedding 常用于什么？",
        "options": ["A. 语义相似度检索", "B. 修改电脑密码", "C. 压缩视频"],
        "answer": "A",
        "difficulty": 2,
        "topic": "RAG",
    },
    {
        "term": "Retrieval",
        "meaning": "检索",
        "explanation": "从知识库中找到与用户问题相关的信息。",
        "example_en": "The retrieval step selects relevant passages from the knowledge base.",
        "example_cn": "检索步骤会从知识库中选择相关段落。",
        "question": "Retrieval 在 RAG 中负责什么？",
        "options": ["A. 查找相关资料", "B. 训练显卡", "C. 注册用户"],
        "answer": "A",
        "difficulty": 2,
        "topic": "RAG",
    },
    {
        "term": "Grounding",
        "meaning": "依据约束 / 事实落地",
        "explanation": "让模型的回答建立在指定数据、文档或现实信息之上。",
        "example_en": "Grounding the answer in company data improves reliability.",
        "example_cn": "让回答基于公司数据可以提高可靠性。",
        "question": "Grounding 的主要价值是什么？",
        "options": ["A. 让回答有事实依据", "B. 降低屏幕亮度", "C. 删除知识库"],
        "answer": "A",
        "difficulty": 3,
        "topic": "AI Safety",
    },
    {
        "term": "Agentic workflow",
        "meaning": "智能体工作流",
        "explanation": "模型根据目标分步骤决策，并调用工具完成任务的工作流程。",
        "example_en": "The agentic workflow checks inventory before placing the order.",
        "example_cn": "智能体工作流会在下单前检查库存。",
        "question": "Agentic workflow 与普通问答最大的区别是什么？",
        "options": ["A. 可以分步骤并调用工具", "B. 不使用模型", "C. 只能输出图片"],
        "answer": "A",
        "difficulty": 3,
        "topic": "Agents",
    },
]
