def _content_item(term, meaning, explanation, example_en, example_cn, difficulty, topic):
    return {
        "term": term,
        "meaning": meaning,
        "explanation": explanation,
        "example_en": example_en,
        "example_cn": example_cn,
        "question": f"{term} 在 AI 行业语境中主要指什么？",
        "options": [
            f"A. {meaning}",
            "B. 一种办公硬件或网络设备",
            "C. 与 AI 无关的日常行政流程",
        ],
        "answer": "A",
        "difficulty": difficulty,
        "topic": topic,
    }


_AI_TERMS = [
    ("Prompt", "提示词", "提供给模型的指令、问题或上下文，用于引导模型生成结果。", "A clear prompt usually produces a more useful answer.", "清晰的提示词通常能产生更有用的回答。", 1, "AI Basics"),
    ("Token", "词元", "模型处理文本时使用的基本单位，可以是一个词、词的一部分或标点。", "The model converts the sentence into tokens before processing it.", "模型在处理句子前会先把它转换成词元。", 1, "LLM"),
    ("Inference", "推理", "训练完成后，模型使用已有参数处理新输入并生成结果的过程。", "The device can run AI inference locally.", "这台设备可以在本地运行 AI 推理。", 1, "LLM"),
    ("Fine-tuning", "微调", "在预训练模型基础上，使用特定数据继续训练，以适应特定任务。", "The team fine-tuned the model on customer service conversations.", "团队使用客服对话数据对模型进行了微调。", 2, "Training"),
    ("Hallucination", "幻觉", "模型生成听起来合理、但事实上错误或没有依据的信息。", "Retrieval can reduce hallucination, but it cannot eliminate it completely.", "检索可以减少幻觉，但不能完全消除它。", 2, "AI Safety"),
    ("Context window", "上下文窗口", "模型一次请求中能够处理和参考的 token 范围。", "A larger context window allows the model to read longer documents.", "更大的上下文窗口让模型能够读取更长的文档。", 2, "LLM"),
    ("Embedding", "嵌入向量", "将文本、图片等内容转换成数值向量，用于表示语义并计算相似度。", "We use embeddings to find semantically similar documents.", "我们使用嵌入向量寻找语义相似的文档。", 2, "RAG"),
    ("Retrieval", "检索", "从知识库中找到与用户问题相关的信息。", "The retrieval step selects relevant passages from the knowledge base.", "检索步骤会从知识库中选择相关段落。", 2, "RAG"),
    ("Grounding", "依据约束 / 事实落地", "让模型的回答建立在指定数据、文档或现实信息之上。", "Grounding the answer in company data improves reliability.", "让回答基于公司数据可以提高可靠性。", 3, "AI Safety"),
    ("Agentic workflow", "智能体工作流", "模型根据目标分步骤决策，并调用工具完成任务的工作流程。", "The agentic workflow checks inventory before placing the order.", "智能体工作流会在下单前检查库存。", 3, "Agents"),
    ("Large language model", "大语言模型", "基于大量文本训练、能够理解和生成语言的模型。", "A large language model can draft emails, summarize reports, and answer questions.", "大语言模型可以写邮件、总结报告并回答问题。", 1, "LLM"),
    ("Generative AI", "生成式 AI", "能够生成文本、图片、音频、视频或代码等新内容的 AI 技术。", "Generative AI can help designers create many concept drafts quickly.", "生成式 AI 可以帮助设计师快速创建多个概念草稿。", 1, "AI Basics"),
    ("Machine learning", "机器学习", "让系统从数据中学习规律，而不是完全依赖人工编写规则。", "Machine learning models improve as they see more relevant examples.", "机器学习模型会随着更多相关样本而改进。", 1, "AI Basics"),
    ("Deep learning", "深度学习", "使用多层神经网络从数据中学习复杂模式的机器学习方法。", "Deep learning is widely used in speech recognition and computer vision.", "深度学习广泛用于语音识别和计算机视觉。", 1, "AI Basics"),
    ("Neural network", "神经网络", "由多层节点组成、用于学习输入和输出之间关系的模型结构。", "A neural network learns patterns from labeled examples.", "神经网络会从带标签样本中学习模式。", 1, "AI Basics"),
    ("Parameter", "参数", "模型训练后保存的数值，用来决定模型如何处理输入。", "A model with more parameters is not always better for every task.", "参数更多的模型并不总是适合每个任务。", 1, "LLM"),
    ("Pretraining", "预训练", "在大规模通用数据上训练模型，为后续任务打基础。", "Pretraining gives the model broad language knowledge.", "预训练让模型获得广泛的语言知识。", 2, "Training"),
    ("Training data", "训练数据", "用于训练模型、帮助模型学习规律的数据集合。", "Poor training data can lead to poor model behavior.", "质量差的训练数据会导致模型表现变差。", 1, "Training"),
    ("Dataset", "数据集", "按特定目的收集、整理并用于分析或训练的数据。", "The team created a dataset of support tickets.", "团队创建了一个客服工单数据集。", 1, "Data"),
    ("Label", "标签", "为数据样本标注的目标答案、类别或属性。", "Each image has a label that describes the object inside it.", "每张图片都有一个描述其中物体的标签。", 1, "Data"),
    ("Annotation", "数据标注", "为原始数据添加标签、说明或结构化信息的过程。", "Accurate annotation is important for supervised learning.", "准确的数据标注对监督学习很重要。", 1, "Data"),
    ("Supervised learning", "监督学习", "使用带正确答案的数据训练模型的方法。", "Supervised learning requires examples with labels.", "监督学习需要带标签的样本。", 2, "Training"),
    ("Unsupervised learning", "无监督学习", "从没有人工答案的数据中发现结构或模式的方法。", "Unsupervised learning can find hidden groups in customer data.", "无监督学习可以在客户数据中发现隐藏分组。", 2, "Training"),
    ("Reinforcement learning", "强化学习", "模型通过奖励和惩罚学习行动策略的方法。", "Reinforcement learning is often used in games and robotics.", "强化学习常用于游戏和机器人领域。", 2, "Training"),
    ("RLHF", "基于人类反馈的强化学习", "利用人类偏好反馈调整模型输出，使其更符合用户期待。", "RLHF can make a chatbot more helpful and safer.", "RLHF 可以让聊天机器人更有帮助且更安全。", 3, "Training"),
    ("Instruction tuning", "指令微调", "用指令和回答样本训练模型，让模型更擅长遵循人类指令。", "Instruction tuning helps the model follow user requests.", "指令微调帮助模型更好地遵循用户请求。", 2, "Training"),
    ("Alignment", "对齐", "让模型行为更符合人类意图、价值和安全要求的过程。", "Alignment work reduces harmful or unwanted outputs.", "对齐工作会减少有害或不符合预期的输出。", 3, "AI Safety"),
    ("Safety filter", "安全过滤器", "用于识别、拦截或改写高风险内容的保护机制。", "The safety filter blocked the harmful request.", "安全过滤器拦截了有害请求。", 2, "AI Safety"),
    ("Guardrail", "护栏机制", "限制模型行为边界、降低风险的规则或系统设计。", "Guardrails keep the assistant within the approved workflow.", "护栏机制让助手保持在批准的流程内。", 2, "AI Safety"),
    ("Evaluation", "评测", "用指标、测试集或人工判断衡量模型效果的过程。", "Evaluation should include both accuracy and user experience.", "评测应同时包含准确性和用户体验。", 1, "Evaluation"),
    ("Benchmark", "基准测试", "用于比较模型能力的一组标准任务或数据集。", "The new model performed well on the benchmark.", "新模型在基准测试中表现很好。", 2, "Evaluation"),
    ("Accuracy", "准确率", "模型预测正确的比例。", "Accuracy is useful, but it is not the only metric.", "准确率有用，但不是唯一指标。", 1, "Evaluation"),
    ("Precision", "精确率", "模型判定为正例的结果中实际正确的比例。", "High precision means fewer false alarms.", "高精确率意味着更少误报。", 2, "Evaluation"),
    ("Recall", "召回率", "所有真实正例中被模型找出来的比例。", "High recall is important when missing a case is costly.", "漏掉案例代价很高时，高召回率很重要。", 2, "Evaluation"),
    ("F1 score", "F1 分数", "综合精确率和召回率的评测指标。", "The F1 score balances precision and recall.", "F1 分数平衡了精确率和召回率。", 2, "Evaluation"),
    ("Latency", "延迟", "系统从收到请求到返回结果所花的时间。", "Low latency is critical for real-time assistants.", "低延迟对实时助手很关键。", 1, "Product"),
    ("Throughput", "吞吐量", "系统在单位时间内能够处理的请求数量。", "Higher throughput allows the service to handle more users.", "更高吞吐量让服务能处理更多用户。", 2, "Product"),
    ("Rate limit", "速率限制", "对单位时间内请求数量设置上限的机制。", "The API returned an error because we hit the rate limit.", "因为触发速率限制，API 返回了错误。", 1, "Product"),
    ("Cost per token", "每 token 成本", "模型按输入和输出 token 计费时的单位成本。", "Cost per token affects the budget of a chatbot product.", "每 token 成本会影响聊天机器人产品预算。", 2, "Product"),
    ("Model serving", "模型服务化", "将模型部署成可供应用调用的在线服务。", "Model serving turns a trained model into a usable API.", "模型服务化会把训练好的模型变成可用 API。", 2, "Infrastructure"),
    ("API endpoint", "API 端点", "应用调用模型或服务时访问的具体网络地址。", "The client sends each request to the API endpoint.", "客户端把每个请求发送到 API 端点。", 1, "Infrastructure"),
    ("Batching", "批处理", "把多个请求合并处理，以提高资源利用率。", "Batching can improve throughput but may increase latency.", "批处理能提高吞吐量，但可能增加延迟。", 2, "Infrastructure"),
    ("Caching", "缓存", "保存常用结果，避免重复计算或重复请求。", "Caching frequent answers can reduce cost and latency.", "缓存常见答案可以降低成本和延迟。", 1, "Infrastructure"),
    ("Vector database", "向量数据库", "用于存储和检索嵌入向量的数据库。", "A vector database helps the app find similar documents quickly.", "向量数据库帮助应用快速找到相似文档。", 2, "RAG"),
    ("Similarity search", "相似度搜索", "根据向量距离查找语义相近内容的方法。", "Similarity search found the most relevant policy pages.", "相似度搜索找到了最相关的政策页面。", 2, "RAG"),
    ("Chunking", "文本切块", "把长文档拆成较小片段，便于检索和引用。", "Good chunking improves retrieval quality.", "好的文本切块能提升检索质量。", 2, "RAG"),
    ("Reranking", "重排序", "对初步检索结果再次排序，优先保留最相关内容。", "Reranking moved the best passage to the top.", "重排序把最佳段落移到了最前面。", 3, "RAG"),
    ("Citation", "引用来源", "模型回答中指向资料出处的说明。", "The assistant included citations for every claim.", "助手为每个说法都提供了引用来源。", 1, "RAG"),
    ("Knowledge base", "知识库", "供模型检索、引用或回答问题的结构化资料集合。", "The knowledge base contains product manuals and policy documents.", "知识库包含产品手册和政策文档。", 1, "RAG"),
    ("RAG", "检索增强生成", "先检索相关资料，再让模型基于资料生成回答的方法。", "RAG helps the model answer with up-to-date company knowledge.", "RAG 帮助模型基于最新公司知识回答。", 2, "RAG"),
    ("System prompt", "系统提示词", "对模型角色、边界和回答风格的最高优先级指令。", "The system prompt tells the assistant to be concise.", "系统提示词要求助手保持简洁。", 1, "Prompting"),
    ("User prompt", "用户提示词", "用户在一次对话中直接输入的问题或指令。", "The user prompt asked the model to summarize the article.", "用户提示词要求模型总结文章。", 1, "Prompting"),
    ("Few-shot prompting", "少样本提示", "在提示词中提供少量示例，引导模型按同样格式回答。", "Few-shot prompting can improve structured outputs.", "少样本提示可以改善结构化输出。", 2, "Prompting"),
    ("Zero-shot prompting", "零样本提示", "不提供示例，直接让模型完成任务的提示方法。", "Zero-shot prompting works well for simple classification tasks.", "零样本提示适合简单分类任务。", 1, "Prompting"),
    ("Chain of thought", "思维链", "让模型分步骤推理的一类提示或推理方式。", "Chain-of-thought prompting can help with complex reasoning.", "思维链提示可以帮助复杂推理。", 3, "Prompting"),
    ("Prompt injection", "提示词注入", "用户试图通过输入破坏或绕过系统指令的攻击方式。", "Prompt injection can cause the model to ignore safety rules.", "提示词注入可能导致模型忽略安全规则。", 3, "AI Safety"),
    ("Jailbreak", "越狱提示", "诱导模型绕过安全限制并输出违规内容的提示方式。", "The jailbreak attempt was blocked by the safety system.", "越狱提示被安全系统拦截了。", 3, "AI Safety"),
    ("Tool calling", "工具调用", "模型根据任务选择并调用外部工具或 API 的能力。", "Tool calling lets the assistant check calendar availability.", "工具调用让助手可以检查日历空闲时间。", 2, "Agents"),
    ("Function calling", "函数调用", "模型以结构化参数调用预定义函数的能力。", "Function calling converts a user request into valid parameters.", "函数调用把用户请求转换成有效参数。", 2, "Agents"),
    ("Agent", "智能体", "能够理解目标、规划步骤并调用工具完成任务的 AI 系统。", "The agent booked a meeting after checking everyone's schedule.", "智能体检查所有人的日程后预订了会议。", 1, "Agents"),
    ("Planner", "规划器", "智能体中负责拆解任务和安排执行步骤的模块。", "The planner divided the task into three actions.", "规划器把任务拆成了三个动作。", 3, "Agents"),
    ("Executor", "执行器", "智能体中负责调用工具并完成具体动作的模块。", "The executor sent the approved message to the customer.", "执行器把批准后的消息发给了客户。", 3, "Agents"),
    ("Memory", "记忆", "系统保存用户偏好、历史上下文或长期事实的能力。", "Memory helps the assistant remember the user's learning level.", "记忆帮助助手记住用户的学习水平。", 2, "Agents"),
    ("Multimodal", "多模态", "同时处理文本、图像、音频或视频等多种信息形式。", "A multimodal model can understand both text and images.", "多模态模型可以同时理解文本和图片。", 1, "Multimodal"),
    ("Computer vision", "计算机视觉", "让机器理解图片和视频内容的 AI 领域。", "Computer vision can detect defects on a production line.", "计算机视觉可以检测生产线上的缺陷。", 1, "Multimodal"),
    ("OCR", "光学字符识别", "从图片或扫描件中识别文字的技术。", "OCR extracted the text from the receipt image.", "OCR 从收据图片中提取了文字。", 1, "Multimodal"),
    ("Speech recognition", "语音识别", "将语音转换成文本的技术。", "Speech recognition turns customer calls into transcripts.", "语音识别把客户通话转换成文字记录。", 1, "Speech"),
    ("Text-to-speech", "文本转语音", "将文字合成为自然语音的技术。", "Text-to-speech can read the example sentence aloud.", "文本转语音可以朗读例句。", 1, "Speech"),
    ("Voice cloning", "声音克隆", "根据参考音频生成相似音色的技术。", "Voice cloning requires strict consent and safety controls.", "声音克隆需要严格授权和安全控制。", 3, "Speech"),
    ("Speaker diarization", "说话人分离", "在音频中区分不同说话人的技术。", "Speaker diarization shows who spoke during the meeting.", "说话人分离会显示会议中谁说了什么。", 2, "Speech"),
    ("Audio transcription", "音频转写", "把录音内容转换成文字稿的过程。", "Audio transcription made the interview searchable.", "音频转写让访谈内容可以被搜索。", 1, "Speech"),
    ("Synthetic data", "合成数据", "由程序或模型生成、用于训练或测试的数据。", "Synthetic data can help when real data is limited.", "真实数据有限时，合成数据可以提供帮助。", 2, "Data"),
    ("Data cleaning", "数据清洗", "修正、过滤或标准化数据，提高数据质量的过程。", "Data cleaning removed duplicate and invalid records.", "数据清洗去除了重复和无效记录。", 1, "Data"),
    ("Data leakage", "数据泄漏", "训练或评测中不该出现的信息提前进入模型或测试流程。", "Data leakage can make evaluation results look unrealistically good.", "数据泄漏会让评测结果看起来不真实地好。", 3, "Data"),
    ("Bias", "偏见", "模型因数据或设计问题对某些群体或场景产生系统性不公平。", "Bias in the dataset can affect model decisions.", "数据集中的偏见会影响模型决策。", 2, "AI Safety"),
    ("Fairness", "公平性", "模型对不同群体和场景保持合理一致表现的要求。", "Fairness testing is important for hiring tools.", "招聘工具需要进行公平性测试。", 2, "AI Safety"),
    ("Explainability", "可解释性", "让人理解模型为什么给出某个结果的能力。", "Explainability helps users trust high-stakes AI systems.", "可解释性帮助用户信任高风险 AI 系统。", 2, "AI Safety"),
    ("Interpretability", "可解释理解", "分析模型内部机制或特征影响的能力。", "Interpretability research studies how models make decisions.", "可解释性研究会分析模型如何做决定。", 3, "AI Safety"),
    ("Model drift", "模型漂移", "线上数据或用户行为变化导致模型效果下降的现象。", "Model drift can reduce accuracy after a product launch.", "产品上线后模型漂移可能降低准确率。", 2, "Evaluation"),
    ("Monitoring", "监控", "持续观察模型质量、延迟、错误率和成本的过程。", "Monitoring alerted the team when latency increased.", "延迟升高时，监控提醒了团队。", 1, "Infrastructure"),
    ("Observability", "可观测性", "通过日志、指标和追踪理解系统内部状态的能力。", "Observability helps engineers debug AI services in production.", "可观测性帮助工程师调试生产环境中的 AI 服务。", 2, "Infrastructure"),
    ("A/B testing", "A/B 测试", "把用户分成不同组，对比两个版本效果的实验方法。", "A/B testing showed that the shorter reply improved engagement.", "A/B 测试显示更短回复提高了互动率。", 1, "Product"),
    ("Human-in-the-loop", "人在回路中", "让人工参与审核、反馈或决策的 AI 工作流。", "Human-in-the-loop review is useful for sensitive cases.", "敏感场景适合加入人在回路审核。", 2, "Product"),
    ("Content moderation", "内容审核", "识别和处理违规、有害或不适合内容的过程。", "Content moderation protects users and the platform.", "内容审核保护用户和平台。", 1, "AI Safety"),
    ("PII", "个人身份信息", "可用于识别个人身份的数据，如姓名、电话或身份证号。", "The system masks PII before sending text to the model.", "系统在把文本发送给模型前会遮蔽个人身份信息。", 2, "AI Safety"),
    ("Privacy", "隐私", "保护用户数据不被未经授权访问或使用的原则。", "Privacy requirements affect how we store conversation history.", "隐私要求会影响我们如何存储对话历史。", 1, "AI Safety"),
    ("Consent", "授权同意", "在收集、处理或使用用户数据前获得明确许可。", "The app asks for consent before analyzing voice data.", "应用在分析语音数据前会请求授权同意。", 1, "AI Safety"),
    ("On-device AI", "端侧 AI", "在用户设备本地运行模型，而不是把数据发送到云端。", "On-device AI can improve privacy and reduce latency.", "端侧 AI 可以提升隐私并降低延迟。", 2, "Infrastructure"),
    ("Edge AI", "边缘 AI", "在靠近数据来源的边缘设备上运行 AI 的方式。", "Edge AI processes camera data near the factory floor.", "边缘 AI 在靠近工厂现场的位置处理摄像头数据。", 2, "Infrastructure"),
    ("Quantization", "量化", "降低模型数值精度，以减少体积和计算成本的方法。", "Quantization made the model small enough for a mobile device.", "量化让模型小到可以放进移动设备。", 3, "Optimization"),
    ("Distillation", "蒸馏", "用大模型指导小模型学习，从而获得更轻量模型的方法。", "Distillation produced a smaller model with similar behavior.", "蒸馏产生了一个行为相近但更小的模型。", 3, "Optimization"),
    ("Pruning", "剪枝", "移除模型中不重要的连接或参数以提升效率的方法。", "Pruning reduced the model size without a large quality drop.", "剪枝降低了模型大小且质量下降不大。", 3, "Optimization"),
    ("LoRA", "低秩适配", "一种高效微调方法，只训练少量额外参数。", "LoRA lets the team fine-tune a large model with less compute.", "LoRA 让团队用更少算力微调大模型。", 3, "Training"),
    ("Transformer", "Transformer 架构", "基于注意力机制的神经网络架构，是现代大语言模型的基础。", "The transformer architecture changed natural language processing.", "Transformer 架构改变了自然语言处理。", 3, "LLM"),
    ("Attention", "注意力机制", "模型在处理序列时决定哪些信息更重要的机制。", "Attention helps the model focus on relevant words.", "注意力机制帮助模型关注相关词语。", 3, "LLM"),
    ("Temperature", "温度参数", "控制模型输出随机性和创造性的生成参数。", "Lower temperature makes the answer more predictable.", "较低温度会让回答更稳定可预测。", 2, "Prompting"),
    ("Streaming output", "流式输出", "模型边生成边返回内容，而不是等完整答案结束后再返回。", "Streaming output makes the chatbot feel faster.", "流式输出会让聊天机器人感觉更快。", 1, "Product"),
    ("Structured output", "结构化输出", "要求模型按 JSON、表格或固定字段返回结果。", "Structured output makes it easier for software to parse the answer.", "结构化输出让软件更容易解析答案。", 2, "Product"),
    ("Workflow automation", "工作流自动化", "用系统自动完成重复业务步骤的能力。", "Workflow automation routes the request to the right team.", "工作流自动化会把请求转给正确团队。", 1, "Agents"),
    ("Semantic search", "语义搜索", "按含义而不是只按关键词匹配内容的搜索方式。", "Semantic search found documents that used different wording.", "语义搜索找到了用词不同但含义相关的文档。", 2, "RAG"),
]


DEMO_CONTENT = [_content_item(*item) for item in _AI_TERMS]


INDUSTRY_BRIEFINGS = [
    {
        "term": "OpenAI：AI Agent 正在改变工作方式",
        "meaning": "OpenAI 发布研究，强调更强的 Agent 工具会让用户处理更长、更复杂、跨职能的任务。",
        "explanation": "这类趋势说明企业对 Agent 产品的需求会从单点问答转向持续执行、协作和工作流自动化。",
        "example_en": "AI agents are moving from simple answers toward longer, cross-functional work.",
        "example_cn": "AI Agent 正在从简单回答走向更长周期、跨职能的工作。",
        "question": "这条早报最适合提示运营关注什么？",
        "options": [
            "A. Agent 产品会更强调持续服务和工作流",
            "B. AI 只能用于聊天娱乐",
            "C. 企业不再需要自动化工具",
        ],
        "answer": "A",
        "difficulty": 1,
        "topic": "AI 行业早报",
        "content_type": "briefing",
        "product_key": "ai_briefing",
        "review_status": "approved",
        "source_url": "https://openai.com/index/how-agents-are-transforming-work/",
    },
    {
        "term": "Anthropic：Claude Tag 强化团队协作场景",
        "meaning": "Anthropic 新闻页显示 Claude Tag 属于近期产品动态，指向团队协作和内容组织类 AI 用法。",
        "explanation": "对付费 Agent 产品来说，标签、上下文和团队协同会成为提高留存的重要能力。",
        "example_en": "Better tagging and context management can make AI workflows easier to operate.",
        "example_cn": "更好的标签和上下文管理可以让 AI 工作流更容易运营。",
        "question": "这条资讯对我们的后台设计有什么启发？",
        "options": [
            "A. 用户、内容和订阅都需要标签体系",
            "B. 后台不需要管理内容",
            "C. 所有用户只能接收同一种内容",
        ],
        "answer": "A",
        "difficulty": 1,
        "topic": "AI 行业早报",
        "content_type": "briefing",
        "product_key": "ai_briefing",
        "review_status": "approved",
        "source_url": "https://www.anthropic.com/news",
    },
    {
        "term": "OpenAI：企业 AI 进入下一阶段",
        "meaning": "OpenAI 企业 AI 动态强调 Agent 在企业范围内落地，推动个人和团队的生产力提升。",
        "explanation": "这说明 B 端和私域用户都可能为持续型 Agent 服务付费，而不是只购买一次性内容。",
        "example_en": "Enterprise AI adoption is shifting toward agents that support teams and workflows.",
        "example_cn": "企业 AI 采用正在转向支持团队和工作流的 Agent。",
        "question": "这条早报最适合作为哪类产品的内容？",
        "options": [
            "A. AI 行业早报",
            "B. 餐厅点餐系统",
            "C. 天气播报",
        ],
        "answer": "A",
        "difficulty": 1,
        "topic": "AI 行业早报",
        "content_type": "briefing",
        "product_key": "ai_briefing",
        "review_status": "approved",
        "source_url": "https://openai.com/index/next-phase-of-enterprise-ai/",
    },
]
